name: library_vacant_seat
description: "Application that displays available seats in UEC library"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0
  http: ^1.2.1
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0-nullsafety
  chewie: ^1.2.2
  video_player: ^2.1.10
  photo_view: ^0.15.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/

